/**
 * Environment Generator Script
 * 
 * This tool reads environment variables from .env files or the system process,
 * and generates a typed TypeScript configuration file for the Angular application.
 * 
 * Features:
 * - Reads from .env locally
 * - Uses process.env for CI/CD environments (GitHub Actions, Docker, etc.)
 * - Automatically picks up any variable prefixed with 'APP_'
 * - Generates environment.auto.ts which is ignored by git
 */
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load .env if it exists
const root = process.cwd();
const envPath = path.join(root, '.env');

if (fs.existsSync(envPath)) {
  console.log('✅ Found .env file, loading variables...');
  dotenv.config({ path: envPath });
} else {
  console.log('ℹ️ .env not found; using system environment variables.');
}

/**
 * Standard variables mapping with defaults
 */
const config = {
  apiUrl: process.env.API_URL || 'http://localhost:3000',
  spotifyClientId: process.env.SPOTIFY_CLIENT_ID || 'YOUR_SPOTIFY_CLIENT_ID',
  spotifyRedirectUri: process.env.SPOTIFY_REDIRECT_URI || 'http://localhost:4200/callback',
};

/**
 * Automatic discovery of variables starting with APP_
 */
Object.keys(process.env).forEach(key => {
  if (key.startsWith('APP_')) {
    const camelKey = key
      .toLowerCase()
      .split('_')
      .map((word, index) => index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    
    // Remove the 'app' prefix if it exists to keep it clean (e.g. APP_VERSION -> version)
    const finalKey = camelKey.startsWith('app') ? camelKey.slice(3).charAt(0).toLowerCase() + camelKey.slice(4) : camelKey;
    config[finalKey] = process.env[key];
  }
});

const outDir = path.join(root, 'src', 'environments');
const outFile = path.join(outDir, 'environment.auto.ts');

// Create directory if it doesn't exist
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const content = `/**
 * AUTO-GENERATED ENVIRONMENT CONFIGURATION
 * 
 * This file is generated by tools/generate-env.js.
 * DO NOT EDIT DIRECTLY.
 * 
 * Variables mapped:
${Object.keys(config).map(k => ` * - ${k}`).join('\n')}
 */
export const environmentAuto = {
${Object.keys(config).map(k => `  ${k}: '${config[k]}',`).join('\n')}
};
`;

try {
  fs.writeFileSync(outFile, content, { encoding: 'utf8' });
  console.log(`✨ Generated: ${path.relative(root, outFile)}`);
  console.log('🚀 Ready to build/serve!');
} catch (error) {
  console.error('❌ Failed to write environment file:', error.message);
  process.exit(1);
}
